server:
  port: 8100
spring:
  application:
    name: kg-gateway
  cloud:
    nacos:
      discovery:
        # 配置 nacos 地址
        # server-addr: 10.1.9.36:8848
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
          # 允许小写服务名称，默认服务名称为大写
          lower-case-service-id: true
      routes:
        # 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: asset_routh
          # 匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://kg-asset-service
          # 断言,路径相匹配的进行路由 替换为 xxx-service/assets/* 其中service由nacos作负载均衡替换为实际主机和端口号
          predicates:
            - Path=/asset/*
