server:
  port: 8001

spring:
  application:
    name: kg-asset-service
  cloud:
    nacos:
      discovery:
        # 配置 nacos 地址
        # server-addr: 10.1.9.36:8848
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
